version: '3.7'

services:
  dev:
    container_name: value-analysis-dev
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
